#!/bin/sh
if [ -n "$1" ]; then
    argum=$1
  else
    argum="tmp"
fi
outputTextFile="multPhiCorr_${argum}_cfi.py"
rm -rf $outputTextFile
echo "import FWCore.ParameterSet.Config as cms">>$outputTextFile
echo "multPhiCorr_${argum} = cms.VPSet(">>$outputTextFile
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_DY_mult.pdf" --map=h --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,3000 --rebin=5 --yZoomRange=-40,40 --xZoomRange=0,4000
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_TT_mult.pdf" --map=h --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,3000 --rebin=5 --yZoomRange=-40,40 --xZoomRange=0,4000
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_DY.pdf" --map=h --mode=sumPt --func='(x*[0]+x**2*[1])*(x<1000) + (x*[2]+x**2*[3])*(x>1000)' --fitRange=0,3000 --rebin=5 --yZoomRange=-40,40 --xZoomRange=0,4000
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_TT.pdf" --map=h --mode=sumPt --func='(x*[0]+x**2*[1])*(x<1000) + (x*[2]+x**2*[3])*(x>1000)' --fitRange=0,3000 --rebin=5 --yZoomRange=-40,40 --xZoomRange=0,4000
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0Barrel_DY_mult.pdf" --map=h0Barrel --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,40 --rebin=5 --yZoomRange=-1,1 --xZoomRange=0,50
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0Barrel_TT_mult.pdf" --map=h0Barrel --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,40 --rebin=5 --yZoomRange=-1,1 --xZoomRange=0,50
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0Barrel_DY_sumPt.pdf" --map=h0Barrel --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,100 --rebin=5 --yZoomRange=-1,1 --xZoomRange=0,100
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0Barrel_TT_sumPt.pdf" --map=h0Barrel --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,100 --rebin=5 --yZoomRange=-1,1 --xZoomRange=0,100
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapPlus_DY_mult.pdf" --map=h0EndcapPlus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,40 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,50
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapPlus_TT_mult.pdf" --map=h0EndcapPlus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,40 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,50
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapPlus_DY_sumPt.pdf" --map=h0EndcapPlus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,150
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapPlus_TT_sumPt.pdf" --map=h0EndcapPlus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,150
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapMinus_DY_mult.pdf" --map=h0EndcapMinus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,40 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,50
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapMinus_TT_mult.pdf" --map=h0EndcapMinus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,40 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,50
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapMinus_DY_sumPt.pdf" --map=h0EndcapMinus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,150
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h0EndcapMinus_TT_sumPt.pdf" --map=h0EndcapMinus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=5 --yZoomRange=-10,10 --xZoomRange=0,150
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaBarrel_DY_mult.pdf" --map=gammaBarrel --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,500 --rebin=0 --yZoomRange=-2,2 --xZoomRange=0,500
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaBarrel_TT_mult.pdf" --map=gammaBarrel --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,500 --rebin=0 --yZoomRange=-2,2 --xZoomRange=0,500
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaBarrel_DY_sumPt.pdf" --map=gammaBarrel --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,400 --rebin=0 --yZoomRange=-2,2 --xZoomRange=0,400
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaBarrel_TT_sumPt.pdf" --map=gammaBarrel --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,400 --rebin=0 --yZoomRange=-2,2 --xZoomRange=0,400
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapPlus_DY_mult.pdf" --map=gammaEndcapPlus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,100 --yZoomRange=-10,10 --xZoomRange=0,100
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapPlus_TT_mult.pdf" --map=gammaEndcapPlus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,100 --yZoomRange=-10,10 --xZoomRange=0,100
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapPlus_DY_sumPt.pdf" --map=gammaEndcapPlus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --yZoomRange=-10,10 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapPlus_TT_sumPt.pdf" --map=gammaEndcapPlus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --yZoomRange=-10,10 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapMinus_DY_mult.pdf" --map=gammaEndcapMinus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,100 --yZoomRange=-10,10 --xZoomRange=0,100
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapMinus_TT_mult.pdf" --map=gammaEndcapMinus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,100 --yZoomRange=-10,10 --xZoomRange=0,100
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapMinus_DY_sumPt.pdf" --map=gammaEndcapMinus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --yZoomRange=-10,10 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/gammaEndcapMinus_TT_sumPt.pdf" --map=gammaEndcapMinus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --yZoomRange=-10,10 --xZoomRange=0,300
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Plus_DY_mult.pdf" --map=h_HF_Plus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Plus_TT_mult.pdf" --map=h_HF_Plus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Plus_DY_sumPt.pdf" --map=h_HF_Plus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Plus_TT_sumPt.pdf" --map=h_HF_Plus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Minus_DY_mult.pdf" --map=h_HF_Minus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Minus_TT_mult.pdf" --map=h_HF_Minus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Minus_DY_sumPt.pdf" --map=h_HF_Minus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/h_HF_Minus_TT_sumPt.pdf" --map=h_HF_Minus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Plus_DY_mult.pdf" --map=egamma_HF_Plus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Plus_TT_mult.pdf" --map=egamma_HF_Plus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Plus_DY_sumPt.pdf" --map=egamma_HF_Plus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,150
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Plus_TT_sumPt.pdf" --map=egamma_HF_Plus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,150
python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Minus_DY_mult.pdf" --map=egamma_HF_Minus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Minus_TT_mult.pdf" --map=egamma_HF_Minus --mode=multiplicity --func='(x*[0]+x**2*[1])' --fitRange=0,300 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,300
#python multiplicityFit.py --textFileName=$outputTextFile --input=DYJetsToLL_M-50_HT-100toInf_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Minus_DY_sumPt.pdf" --map=egamma_HF_Minus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,150
#python multiplicityFit.py --textFileName=$outputTextFile --input=TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola_Phys14DR-PU20bx25_PHYS14_25_V1-v1_AODSIM.root --rootGDir=pfMEtMultCorrInfoWriter --plotFileName="/afs/hephy.at/user/s/schoefbeck/www/pngPF2/egamma_HF_Minus_TT_sumPt.pdf" --map=egamma_HF_Minus --mode=sumPt --func='(x*[0]+x**2*[1])' --fitRange=0,150 --rebin=0 --yZoomRange=-4,4 --xZoomRange=0,150
echo ")">>$outputTextFile
echo "Outputs written to: $outputTextFile"
